export default {
    'cliente.codigoCliente': 'Client Code',
    'cliente.TipoIdentificacion': 'Identification type',
    'cliente.nombre': 'Name',
    'cliente.identificacion': 'Identification',
    'cliente.estado': 'State',
    'cliente.agregarCliente': 'Add Client',
    'cliente.modificarCliente': 'Modify Client',
    'cliente.correoElectronico': 'Email',
    'cliente.NoInformaCorreo': 'Does not report mail',
    'cliente.celular': 'cellphone',
    'cliente.NoInformaCelular': 'Does not report cellphone',
    'cliente.AutorizaEmail': 'Authorization to send notifications by email',
    'cliente.AutorizaMensaje': 'Authorization to send notifications via text message',
    'cliente.HabeasData':
        'Mr. User, do you authorize the inclusion of the information provided in our database, in accordance with the provisions of our privacy policy',
    'cliente.tratamientoDatos': 'processing of personal data?',
    'cliente.direccion': 'Address',
    'cliente.HabeasDataSi': 'Yes',
    'cliente.HabeasDataNo': 'No',
    'cliente.mismosDatosPrincipal': 'Same Principal Data',
    'cliente.agregarClienteContacto': 'Add client contact',
    'cliente.modificarClienteContacto': 'Modify client contact',
    'cliente.UbicacionesCliente': 'Client Ubications',
    'cliente.NoHayClientes': 'No customers found',
    'cliente.LlenarValoresObligatorios': 'The identification and document type are required',
    'cliente.NoHayUbicaciones': 'Ngit log o ubications found for that client',
    'cliente.preguntaCreacionCliente': 'Do you want to create a customer?',
};
