export default {
    // TablaUsuariosPersona
    'TablaUsuariosPersona.AbreviaturaNumeroIdentificacion': 'Identification',
    'TablaUsuariosPersona.DescripcionTipoUsuario': 'User type',
    'TablaUsuariosPersona.DigitoVerificacion': 'Verification digit',
    'TablaUsuariosPersona.Nombres': 'Names',
    'TablaUsuariosPersona.Direccion': 'Address',
    'TablaUsuariosPersona.EmailPrincipal': 'Primary Email',
    'TablaUsuariosPersona.EmailAlterno': 'Alternate email',
    'TablaUsuariosPersona.Celular': 'Cell Phone',
    'TablaUsuariosPersona.Login': 'Login',
    'TablaUsuariosPersona.DescripcionEstado': 'State',
    'TablaUsuariosPersona.EstadoGlobal': 'State',
    'TablaUsuariosPersona.Activo': 'Active',
    'TablaUsuariosPersona.Inactivo': 'Inactive',
    'TablaUsuariosPersona.TipoIdentificacion': 'Identification type',
    'TablaUsuariosPersona.NumeroIdentificacion': 'Identification number',
    // ModalUsuariosPersona
    'ModalUsuariosPersona.TituloCreacion': 'Crate user',
    'ModalUsuariosPersona.TituloEdicion': 'Edit user',
    // FormularioPersona
    'FormularioPersona.IdTipoIdentificacion': 'Identification type',
    'FormularioPersona.NumeroIdentificacion': 'Identification number',
    'FormularioPersona.DigitoDeVerificacion': 'Check digit',
    'FormularioPersona.PrimerNombre': 'First name',
    'FormularioPersona.SegundoNombre': 'Second name',
    'FormularioPersona.PrimerApellido': 'First surname',
    'FormularioPersona.SegundoApellido': 'Second surname',
    'FormularioPersona.Direccion': 'Address',
    'FormularioPersona.Telefonos': 'Phone',
    'FormularioPersona.EmailPrincipal': 'Primary Email',
    'FormularioPersona.EmailAlterno': 'Alternate email',
    'FormularioPersona.Celular': 'Cell Phone',
    'FormularioPersona.Estado': 'State',
    'FormularioUsuario.CaracteresClave': 'The key must contain at least 8 characters.',
    'FormularioEmpresa.NumeroIdentificacionMaxCara': 'The identification accepts a maximum of 12 characters.',
    'FormularioUsuario.CorreoInvalido': 'Invalid email',
    'FormularioPersona.CorreoInvalido': 'Invalid email',
    'Usuario.UsusarioSinPermisos': 'User without permission',
    // FormularioUsuario
    'FormularioUsuario.IdTipoUsuario': 'User type',
    'FormularioUsuario.Login': 'Users',
    'FormularioUsuario.CorreoElectronico': 'Email',
    'FormularioUsuario.Clave': 'Password',
    'FormularioUsuario.ConfirmacionClave': 'Password confirmation',
    'FormularioUsuario.Foto': 'Photo',
    'FormularioUsuario.ValidacionConfirmacionClave': 'Password do not match',
    // FormularioUsuarioPerfilAgencia
    'FormularioUsuarioPerfilAgencia.IdAgencia': 'Agency',
    'FormularioUsuarioPerfilAgencia.NoAgencias': 'There are no agencies',
    'FormularioUsuarioPerfilAgencia.IdPerfil': 'Profile',
    'FormularioUsuarioPerfilAgencia.NoPerfiles': 'No profiles',
    'FormularioUsuarioPerfilAgencia.AgenciaPorDefecto': 'Default',
    'FormularioUsuarioPerfilAgencia.NoAgenciasAnadidas': 'There are no agencies',
    'FormularioUsuarioPerfilAgencia.ConfirmacionEliminarAgencia': 'Are you sure you want to delete the agency?',
    'FormularioUsuarioPerfilAgencia.Si': 'Yes',
    'FormularioUsuarioPerfilAgencia.No': 'No',
    'FormularioUsuarioPerfilAgencia.BotonAgregar': 'Add',
    'FormularioUsuarioPerfilAgencia.ValidacionModificacionUsuarioPorDefecto':
        'You must select another agency-profile by default before',
};
