export default {
    'cliente.codigoCliente': 'Código cliente',
    'cliente.TipoIdentificacion': 'Tipo identificación',
    'cliente.nombre': 'Nombre',
    'cliente.identificacion': 'Identificación',
    'cliente.estado': 'Estado',
    'cliente.agregarCliente': 'Agregar Cliente',
    'cliente.modificarCliente': 'Modificar Cliente',
    'cliente.correoElectronico': 'Correo electrónico',
    'cliente.NoInformaCorreo': 'No reporta correo',
    'cliente.celular': 'Celular',
    'cliente.NoInformaCelular': 'No reporta celular',
    'cliente.AutorizaEmail': 'Autorización envío de notificaciones mediante correo electrónico',
    'cliente.AutorizaMensaje': 'Autorización envío de notificaciones mediante mensaje de texto',
    'cliente.HabeasData':
        'Señor usuario, ¿Usted autoriza que se incluya la información suministrada en nuestra base de datos, de acuerdo con lo establecido en nuestra política de ',
    'cliente.tratamientoDatos': 'tratamiento de datos personales?',
    'cliente.direccion': 'Dirección',
    'cliente.HabeasDataSi': 'Si',
    'cliente.HabeasDataNo': 'No',
    'cliente.mismosDatosPrincipal': 'Mismos datos principal',
    'cliente.agregarClienteContacto': 'Agregar contacto de cliente',
    'cliente.modificarClienteContacto': 'Modificar contacto de cliente',
    'cliente.UbicacionesCliente': 'Ubicaciones Cliente',
    'cliente.NoHayClientes': 'No se encontraron clientes',
    'cliente.LlenarValoresObligatorios': 'La identificación y el tipo de documento son obligatorios',
    'cliente.NoHayUbicaciones': 'No se encontraron ubicaciones para el cliente',
    'cliente.preguntaCreacionCliente': '¿Desea crear un cliente?',
};
