export default {
    // TablaUsuariosPersona
    'TablaUsuariosPersona.AbreviaturaNumeroIdentificacion': 'Identificación',
    'TablaUsuariosPersona.DescripcionTipoUsuario': 'Tipo usuario',
    'TablaUsuariosPersona.DigitoVerificacion': 'Dígito verificación',
    'TablaUsuariosPersona.Nombres': 'Nombres',
    'TablaUsuariosPersona.Direccion': 'Dirección',
    'TablaUsuariosPersona.EmailPrincipal': 'Email principal',
    'TablaUsuariosPersona.EmailAlterno': 'Email alterno',
    'TablaUsuariosPersona.Celular': 'Celular',
    'TablaUsuariosPersona.Login': 'Login',
    'TablaUsuariosPersona.DescripcionEstado': 'Estado',
    'TablaUsuariosPersona.EstadoGlobal': 'Estado',
    'TablaUsuariosPersona.Activo': 'Activo',
    'TablaUsuariosPersona.Inactivo': 'Inactivo',
    'TablaUsuariosPersona.TipoIdentificacion': 'Tipo identificación',
    'TablaUsuariosPersona.NumeroIdentificacion': 'Número Identificación',
    // ModalUsuariosPersona
    'ModalUsuariosPersona.TituloCreacion': 'Crear usuario',
    'ModalUsuariosPersona.TituloEdicion': 'Modificar usuario',
    // FormularioPersona
    'FormularioPersona.IdTipoIdentificacion': 'Tipo identificación',
    'FormularioPersona.NumeroIdentificacion': 'Número identificación',
    'FormularioPersona.DigitoDeVerificacion': 'Dígito de verificación',
    'FormularioPersona.PrimerNombre': 'Primer nombre',
    'FormularioPersona.SegundoNombre': 'Segundo nombre',
    'FormularioPersona.PrimerApellido': 'Primer apellido',
    'FormularioPersona.SegundoApellido': 'Segundo apellido',
    'FormularioPersona.Direccion': 'Dirección',
    'FormularioPersona.Telefonos': 'Teléfonos',
    'FormularioPersona.EmailPrincipal': 'Email principal',
    'FormularioPersona.EmailAlterno': 'Email alterno',
    'FormularioPersona.Celular': 'Celular',
    'FormularioPersona.Estado': 'Estado',
    'FormularioUsuario.CaracteresClave': 'La clave debe contener como mínimo 8 caracteres.',
    'FormularioEmpresa.NumeroIdentificacionMaxCara': 'La identificación acepta como máximo 12 caracteres.',
    'FormularioUsuario.CorreoInvalido': 'Correo inválido',
    'FormularioPersona.CorreoInvalido': 'Correo inválido',
    'Usuario.UsusarioSinPermisos': 'Usuario sin permisos',
    // FormularioUsuario
    'FormularioUsuario.IdTipoUsuario': 'Tipo usuario',
    'FormularioUsuario.Login': 'Usuario',
    'FormularioUsuario.CorreoElectronico': 'Correo electrónico',
    'FormularioUsuario.Clave': 'Clave',
    'FormularioUsuario.ConfirmacionClave': 'Confirmación clave',
    'FormularioUsuario.Foto': 'Foto',
    'FormularioUsuario.ValidacionConfirmacionClave': 'Las claves no coinciden',
    // FormularioUsuarioPerfilAgencia
    'FormularioUsuarioPerfilAgencia.IdAgencia': 'Agencia',
    'FormularioUsuarioPerfilAgencia.NoAgencias': 'No hay agencias',
    'FormularioUsuarioPerfilAgencia.IdPerfil': 'Perfil',
    'FormularioUsuarioPerfilAgencia.NoPerfiles': 'No hay perfiles',
    'FormularioUsuarioPerfilAgencia.AgenciaPorDefecto': 'Por defecto',
    'FormularioUsuarioPerfilAgencia.NoAgenciasAnadidas': 'No hay agencias',
    'FormularioUsuarioPerfilAgencia.ConfirmacionEliminarAgencia': '¿Está seguro que desea eliminar la agencia?',
    'FormularioUsuarioPerfilAgencia.Si': 'Sí',
    'FormularioUsuarioPerfilAgencia.No': 'No',
    'FormularioUsuarioPerfilAgencia.BotonAgregar': 'Agregar',
    'FormularioUsuarioPerfilAgencia.ValidacionModificacionUsuarioPorDefecto':
        'Debe seleccionar otra agencia-perfil por defecto antes',
};
